# http://module-build.sourceforge.net/META-spec.html
# #XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Bugzilla3
version:      0.6
version_from: lib/WWW/Bugzilla3.pm
installdirs:  site
requires:
    Carp:       0
    RPC::XML:   0
    RPC::XML::Parser:   0
    LWP::UserAgent:     0
    HTTP::Cookies:      0
    URI::Escape:        0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17

